### ISSUE TITLE
`GCE.launch` does not respect the `wait` parameter

### ISSUE THREAD

**Issue by OddBloke** [canonical/pycloudlib#104]
This leads to cloud-init test failures: we assume that cloud-init will be complete if we pass `wait=True`, and that assumption is broken by GCE's implementation.

**Comment by OddBloke** [comment]
We could fix this by modifying `GCE.launch`'s implementation. I think a better approach (to avoid this category of bug entirely) is to refactor `launch` to be a concrete method on `BaseCloud` which handles pycloudlib's common launch behaviour, and delegates to an abstract `_launch_instance` (which returns a `BaseInstance` instance, which we can then use to `wait`). A rough implementation:

```py
    def launch(self, image_id, instance_type=None, user_data=None,
               wait=True, **kwargs):  # () -> BaseInstance
        instance = self._launch_instance(image_id, instance_type=instance_type, user_data=user_data, **kwargs)
        if wait:
            instance.wait()
        return instance
```

`_launch_instance` will be the current `launch` implementation for each cloud, but with the `wait` keyword argument (and any code that uses it) removed.

One open question I need to consider is defaulting: currently, `GCE.launch` has a default for instance_type (`"n1-standard-1"`) and my proposed implementation above would break that: we would _explicitly_ pass `instance_type=None` to `_launch_instance` in the default case, meaning the default defined on `_launch_instance` would be ignored.

(My initial thought is to make the signature `launch(self, *args, wait=True, **kwargs)`, and the call `self._launch_instance(*args, **kwargs)`; passing `kwargs` around side-steps defaulting in this method.)

**Comment by OddBloke** [comment]
(This is analogous to what we did with `BaseInstance.wait` in 831551d4d0e4bfaf2b9a19ac730ea21aa0e2a4f8.)

**Comment by TheRealFalcon** [comment]
Tbh, I think I'd rather just modify GCE's launch implementation here. It's unfortunate that we hit this particular issue, but it seems unlikely to happen again (especially now that we don't have a custom wait on the cloud-init side), and I don't think removing two lines from each implementation is a huge win.

If we do make a change like this, I really don't want to change the function signature, as I don't want to jump multiple layers deep to find out what I need to pass to the API. I think it's worth adding some annoying argument parsing in order to preserve the signature. E.g., something like
```python
def launch(self, image_id, instance_type=None, user_data=None,
           wait=True, **kwargs):  # () -> BaseInstance
    new_kwargs = {
        'user_data': user_data,
        'wait': wait,
        **kwargs
    }
    if instance_type is not None:
        new_kwargs['instance_type'] = instance_type
    instance = self._launch_instance(image_id, **new_kwargs)
    ...
```

**Comment by OddBloke** [comment]
OK, good call. I'm looking at other clouds, OCI uses `wait` differently to how we use it elsewhere: it waits for OCI to report the instance `RUNNING`, rather than `instance.wait()`. I'll also update that, to unconditionally wait for `RUNNING`, and to call `instance.wait` appropriately.

> I don't want to jump multiple layers deep to find out what I need to pass to the API.

(Aside: wouldn't retaining the description of the arguments in the docstring cover this?)

(Further aside: I wonder if mypy or other static analysers can infer the signature of a wrapper method like that?)
