### ISSUE TITLE
OCI launches without compartment ID do not work

### ISSUE THREAD

**Issue by OddBloke** [canonical/pycloudlib#105]
```pytb
Traceback (most recent call last):
  File "/home/daniel/dev/cloud-init/tests/integration_tests/conftest.py", line 101, in session_cloud
    cloud = platforms[integration_settings.PLATFORM]()
  File "/home/daniel/dev/cloud-init/tests/integration_tests/clouds.py", line 93, in __init__
    self.cloud_instance = self._get_cloud_instance()
  File "/home/daniel/dev/cloud-init/tests/integration_tests/clouds.py", line 239, in _get_cloud_instance
    return OCI(
  File "/home/daniel/dev/pycloudlib/pycloudlib/oci/cloud.py", line 54, in __init__
    raise Exception(exception_text)
Exception: Could not obtain OCI compartment id. Has the CLI client been setup?
Command attempted: 'oci iam compartment get'
stdout: 
stderr: Usage: oci iam compartment get [OPTIONS]

Error: Missing option(s) --compartment-id.
```

Looking at the CLI, it's not clear to me that it does actually have defaults that we can rely on? If I run `oci compute instances list`, it prompts me for a `--compartment-id` also, and I don't see an obvious way of setting a default.

**Comment by OddBloke** [comment]
One thing to note is that the output of `oci iam compartment list` lists multiple compartments, but the _compartment ID_ is in the `id` field rather than the `compartment-id` field (which appears to be a tenancy ID).

(I initially thought that my `~/.oci/config` file had something that matched a compartment ID, and therefore could perhaps be a default, but that is in fact a tenancy.)

**Comment by TheRealFalcon** [comment]
```
$ cat oci_cli_rc 
[DEFAULT]
 # get this from https://console.us-phoenix-1.oraclecloud.com/a/identity/compartments
compartment-id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
```

I could work this into the exception message somehow.

**Comment by OddBloke** [comment]
I have the following in `~/.oci/config`:

```ini
[DEFAULT]
<snip>
compartment-id=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
```

and I still see:

```
$ oci iam compartment get
Usage: oci iam compartment get [OPTIONS]

Error: Missing option(s) --compartment-id.
```

(I wonder if this is another compatibility break?)

**Comment by OddBloke** [comment]
Hmm, looks to me like it's always been required: strange.

**Comment by OddBloke** [comment]
OK, I've figured out what's going on: the methods described in https://pycloudlib.readthedocs.io/en/latest/clouds/oci.html and in the linked Oracle documentation write out `~/.oci/config` including a `[DEFAULT]` section. _However_, `oci` only appears to read the defaults from `~/.oci/oci_cli_rc`: if I copy my `config` to `oci_cli_rc` then defaulting does work.

I have a local branch which drops the defaulting (and thus requires consumers to specify a compartment ID explicitly): I'll push that up as a WIP branch for consideration. A doc fix could work, it looks like there is a setup command for this too: https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.9.7/oci_cli_docs/cmdref/setup/oci-cli-rc.html

**Comment by TheRealFalcon** [comment]
Since this works as expected when the relevant configuration files are configured appropriately, I'm closing this issue.
