### ISSUE TITLE
[RFC] Add support for other distros

### ISSUE THREAD

**Issue by paride** [canonical/pycloudlib#11]
It would be nice to add support for other distros to pycloudlib. This requires some discussion, as currently pycloudlib has been developed around Ubuntu, and adding other distros is likely to require API changes.

The first non-Ubuntu supported distro could be Debian on EC2. Once we have an AMI everything should work more or less as it does with Ubuntu, so probably we just need to modify the `released_image()` and `daily_image()`. These functions normally take a `release=<ubuntu release name>` argument. We could modify them so they take something like:
```
release=<[distribution:]release>
```
with `distribution` defaulting to `ubuntu`. If `distribution = ubuntu` then the Ubuntu streams are queried as we already do. If `distribution = debian` then I think we need to do something like:
```
aws ec2 describe-images --region us-east-1 --owners 136693071363 --filters 'Name=architecture,Values=x86_64' 'Name=name,Values=debian-10-*' 'Name=description,Values=Debian * (*)' --query 'sort_by(Images, &CreationDate)'
```

Ugly, but I don't not aware of better ways. See also: https://wiki.debian.org/Cloud/AmazonEC2Image

In lack of streams I don't think the `image_serial()` function can be adjusted for non-Ubuntu.

**Comment by blackboxsw** [comment]
+1 I think this will be a natural followup after the refactor #9 lands

**Comment by paride** [comment]
Closing per Chad's comment.
