### ISSUE TITLE
SSH connection retrying is handled at multiple levels

### ISSUE THREAD

**Issue by OddBloke** [canonical/pycloudlib#110]
When attempting to run a command via SSH on a host, we call `_ssh_(command, ...)` which, in turn, calls `_ssh_connect`. In [`_ssh_connect`, we retry 60 times, sleeping 10 seconds in-between](https://github.com/canonical/pycloudlib/blob/master/pycloudlib/instance.py#L315-L337):

```py
        retries = 60
        last_exception = None
        while retries:
            try:
                ...
                return client
            except ... as e:
                ...
                retries -= 1
                time.sleep(10)
```

If this fails, however, then `_ssh` _also_ retries: https://github.com/canonical/pycloudlib/blob/ef76d90f8412a932e92212bc2ec0680c109fb324/pycloudlib/instance.py#L263-L269

600s is plenty of time for an SSH connection to happen if it's going to: we should rationalise this waiting so we only perform it in one place.

**Comment by TheRealFalcon** [comment]
This was fixed in #148
