### ISSUE TITLE
lxd: provide mechanism to replace stale pycloudlib-vm-<release> profiles at vm launch time

### ISSUE THREAD

**Issue by blackboxsw** [canonical/pycloudlib#123]
If a profile already exists by the name of  `pycloudlib-vm-<release>` pycloudlib will automatically use that profile at instance launch time instead of recreating that profile.

We already have a mechanism to [force recreating a profile if present in LXD.create_profile(force=True)] https://github.com/canonical/pycloudlib/blob/master/pycloudlib/lxd/cloud.py#L60. This mechanism/param should either be wired up to either the launch command or the LXD cloud instance settings to ensure reuse of integration test runs get the latest profile definitions from pycloudlib.

This failure condition is most prevalent on jenkins worker nodes which have multiple PRs running simultaneously, all of which leverage a common vm profile for all tests.
Ultimately we probably also want  the ability to provide a scoped set of profile names for LXD to create to avoid collisions with mutiple jenkins jobs in parallel.

**Comment by OddBloke** [comment]
Is this a dupe of #65?

**Comment by blackboxsw** [comment]
Yep closing as duplicate  of #65
