### ISSUE TITLE
LXD xenial virtual machines does not supporting running commands through exec

### ISSUE THREAD

**Issue by lucasmoura** [canonical/pycloudlib#132]
To run an `exec` command on a LXD virtual machine, we need to have installed in the machine the `lxd-agent` binary. To install this binary, we need the running kernel to support `vhost-vsock` communication device. This is a problem for `xenial`, since the kernel in that release doesn't support it. To support that, we would need to install the HWE kernel in Xenial or use a different base image that already comes with the HWE kernel installed, like `images:ubuntu/16.04/cloud`.

We believe that using a different image for xenial or installing the HWE kernel is an overkill for this situation. Because of that, we are not supporting running `exec` commands on Xenial LXD virtual machines by default. However, the user is still free to provide a base image source that does support running `exec` commands. In that case, the command should work normally.

**Comment by OddBloke** [comment]
Thanks Lucas, this is an accurate summary of the issue. Closing this out `wontfix` as agreed.

**Comment by paride** [comment]
For future reference: this also affects the ability to pull and push files via `lxc file pull` and `lxc file push`.
