### ISSUE TITLE
Null availability_domain for OCI

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/pycloudlib#138]
https://github.com/canonical/pycloudlib/blob/main/pycloudlib/oci/cloud.py#L185 used to give a valid value, but now it's just giving 'Null'.

I didn't have time to debug, so as a quick workaround, I hardcoded an availability zone:
`availability_domain = 'qIZq:PHX-AD-3' `

With this, tests run again. We should look to see if there's a better long-term solution.

**Comment by OddBloke** [comment]
I don't think this is the same as #105, but we should look at both simultaneously, I suspect.

**Comment by TheRealFalcon** [comment]
https://docs.oracle.com/en-us/iaas/tools/python/2.37.0/api/core/models/oci.core.models.Subnet.html#oci.core.models.Subnet.availability_domain is relevant.
