### ISSUE TITLE
Pycloudlib exception types are too generic, occassionally wrong

### ISSUE THREAD

**Issue by hammerstefan** [canonical/pycloudlib#263]
Pycloudlib is frequently throwing exceptions that are too generic for a use to be able to handle them intelligently.

Too Generic:
There are 25 cases in pycloudlib of `raise Exception(...)`.  Additionally there are 9 cases of `raise RuntimeError()`. When calling code tries to handle that error, there is no clear way to know what or where an error occurred. Syntax Error? Out of local resources? Pycloud misconfigured? Problem with cloud? Out of cloud resources? Network went down? Cloud API library outdated? NotImplementedError? Timeout? Etc, etc. Most cases of the `raise Exception` includes an error description that might be useful to a human, but is near useless for calling python code to handle.

Wrong exception types:
There are 2 cases of `raise OSError()` for cloud interaction errors. That is not a correct exception type. https://docs.python.org/3/library/exceptions.html#OSError. `OSError` is for system-related error raised from a system-related call, usually mapping to a system error code https://docs.python.org/3/library/errno.html#module-errno.

The are 7 cases of `raise TimeoutError()` for cloud interaction errors. This is an `OSError` and should only pertain to local system and maps to ETIMEDOUT system errors. It's best to avoid `OSError` exceptions for remote interactions.

** Rough Proposal **
Create a hierarchy of pycloudlib exceptions with increasing specificity

An example:
```
class PycloudlibError(RuntimeError)
class PycloudlibTimeoutError(PycloudlibError)
class PycloudlibOutOfResourcesError(PycloudlibError)
class OracleError(PycloudlibError)
class OracleTimeoutError(PycloudlibTimeoutError)
class GceError(PycloudlibError)
...
```

Making the "too generic" exceptions more generic should be safe to do, since any existing users that are doing `except Exception` will continue to catch those.  However, this would allow new users to use specific exception handlers for better error handling. Even just switching from `except Exception` to `except PycloudLibError` is a huge improvement, since you eliminate entire categories of errors that didn't want to catch (like syntax errors).

Changing the wrong exception types to more correct types could break existing users.  Ideally we do this with a symver major version release.

Furthermore, whatever exception schema we chose, it needs to be clearly documented since the user has to know how to handle errors.

**Comment by blackboxsw** [comment]
https://warthogs.atlassian.net/browse/SC-1436

**Comment by blackboxsw** [comment]
I think @aciba90 mentioned he was looking at this, so I assigned it to communicate it's getting worked. If this is wrong Alberto, feel free to unassign this letting others know not to work on it.
