### ISSUE TITLE
ec2 cloud.py relies on streams rather than querying the cloud

### ISSUE THREAD

**Issue by j5awry** [canonical/pycloudlib#266]
`EC2._find_image` utilizes streams files. There is a strong preference from the Public Cloud team for users to utilize the in-cloud references to find images. This is publicly documented for ec2: 

https://ubuntu.com/server/docs/cloud-images/amazon-ec2

This should be achievable using `botocore:SSM.Client.get_parameters(name=$FORMATTED_NAME)`. The SSM client configuration can be done using the same client configuration as the EC2 boto client (region, auth, etc). 

This also makes integration with restricted regions or marketplace easier in the future cases (premium Ubuntu images are not contained in streams)

**Comment by TheRealFalcon** [comment]
As of [efcdf6](https://github.com/canonical/pycloudlib/commit/efcdf6712bbbdf526a98545b091f897d484e63a0) `EC2._find_image` is actually dead code. Streams is only used for LXD these days.

**Comment by aciba90** [comment]
Fixed in https://github.com/canonical/pycloudlib/pull/280.
