### ISSUE TITLE
Azure launch VM configuration interfaces for confidential VM and trusted launch

### ISSUE THREAD

**Issue by jrtknauer** [canonical/pycloudlib#298]
While setting these configurations is possible through the vm_params passthrough on the launch method, it would be a beneficial enhancement for pycloudlib to directly support Confidential VM and Trusted Launch configuration as part of the Azure client interface.

As an example, for enabling trusted launch the VM configuration under the current interface, 
```
client = pycloudlib.Azure(...)
trusted_launch_config = {
    "security_profile": {
        "security_type": "TrustedLaunch"
        "uefi_settings": { "secure_boot_enabled": True, "v_tpm_enabled": True }
    }
}
client.launch(..., vm_params=trusted_launch_config)
```

Ideally, the pycloudlib Azure VM configuration interface would match that of the portal, abstracting feature toggles from direct passage of vm_params to encoded enums/flags.

**Comment by aciba90** [comment]
Tracking in SC-1533.
