### ISSUE TITLE
Not all `pycloudlib.instance.BaseInstance` subclasses call `self._wait_for_system`

### ISSUE THREAD

**Issue by OddBloke** [canonical/pycloudlib#35]
### Problem Statement

`BaseInstance` has an abstract `wait` method; this is called when consumers want to wait for the instance to launch and for cloud-init to be complete:

https://github.com/canonical/pycloudlib/blob/1cd00cdc7deed8ae4df927f1a1ff1a25c2349fa0/pycloudlib/instance.py#L87-L90

It also has a concrete `_wait_for_system` method, which performs the waiting for `cloud-init` to complete (this is just the first few lines):

https://github.com/canonical/pycloudlib/blob/1cd00cdc7deed8ae4df927f1a1ff1a25c2349fa0/pycloudlib/instance.py#L361-L363

It follows that whenever `wait` is called, `_wait_for_system` should also be called. However, with the code as-is, we rely on `BaseInstance` subclasses doing so in their implementation of `wait`; they currently don't always.

### Proposed Solution

Instead of fixing up those specific cases for now, I instead propose that we refactor the way that waiting works to ensure that the "call `_wait_for_system` when `wait` is called" invariant will always hold. My proposed steps:

* add a no-op concrete method to `BaseInstance` named `_wait_for_start`
* convert `wait` to a concrete method which calls `self._wait_for_start()` then `self._wait_for_system()`
* remove the implementations of `wait` which currently only call `self._wait_for_system()` (i.e. Azure, LXD, KVM)
* refactor the remaining implementations of `wait` to drop the call to `self._wait_for_system()` (if present), and rename them to `_wait_for_start`

This means that calling `instance.wait()` will always call `self._wait_for_system`, while still allowing cloud-specific waiting to be captured in `self._wait_for_start`.

**Comment by TheRealFalcon** [comment]
Makes sense. Sounds like a good change

**Comment by OddBloke** [comment]
I've got this ready locally, but it'll conflict horribly with #34 if I try to propose it in parallel, so I'll wait until that lands.
