### ISSUE TITLE
Note if pycloudlib requires python 3.7 ++ we need to update our project docs which state python 3.6 https://pypi.org/project/pycloudlib/

### ISSUE THREAD

**Issue by a-dubs** [canonical/pycloudlib#418]
Note if pycloudlib requires python 3.7 ++ we need to update our project docs which state python 3.6 https://pypi.org/project/pycloudlib/

_Originally posted by @blackboxsw in https://github.com/canonical/pycloudlib/pull/407#discussion_r1761676018_

**Comment by aciba90** [comment]
I could potentially remove https://github.com/canonical/pycloudlib/blob/9e0a65eebca7815a1d65b149dc8a21e559cef0fd/setup.cfg#L34 and https://github.com/canonical/pycloudlib/blob/9e0a65eebca7815a1d65b149dc8a21e559cef0fd/setup.cfg#L37 as they are dependency versions for 3.6 only.
