### ISSUE TITLE
lxd launch() fails if name parameter is not specified

### ISSUE THREAD

**Issue by paride** [canonical/pycloudlib#46]
When launching an LXD instance without passing the `name` parameter to `launch()` it fails with error:
```
AttributeError: 'NoneType' object has no attribute 'encode'
```
Pycloudlib should handle this case better, falling back to the container/vm name automatically generated by lxd.

**Comment by OddBloke** [comment]
Can you give an example of where this is failing? We don't pass a name in cloud-init's tests, and we don't see a problem. https://github.com/canonical/cloud-init/blob/db2ff11dea5d884093e4e29393eeac70d3315bbb/tests/integration_tests/clouds.py#L64-L69 are the lines that perform the launch:

```py
        log.info(
            "Launching instance with launch_kwargs:\n{}".format(
                "\n".join("{}={}".format(*item) for item in kwargs.items())
            )
        )
        pycloudlib_instance = self.cloud_instance.launch(**kwargs)
```

and this is the output from that log line (in a test just run locally):

```
INFO     integration_testing:clouds.py:64 Launching instance with launch_kwargs:
image_id=ubuntu:1503148c44359a349c17ce7cd4e0e36dae9ff3a44a7777cc1cee993491a73adf
user_data=#cloud-config
ntp:
  ntp_client: ntp
  servers:
      - 172.16.15.14
      - 172.16.17.18

wait=False
```

The test ran successfully to completion.

**Comment by OddBloke** [comment]
Oh, nope, I didn't have the latest `pycloudlib`. Yeah, this is a regression.
