### ISSUE TITLE
Launching xenial LXD VM images should not default to the images: remote

### ISSUE THREAD

**Issue by OddBloke** [canonical/pycloudlib#48]
The expectation of the cloud-init integration tests is that pycloudlib will operate on official Ubuntu cloud images by default. This is also [the documented expectation in the design doc](https://pycloudlib.readthedocs.io/en/latest/design.html#images):

> Instances are expected to use the latest daily image, unless another image is specifically requested.

For LXD, that means fetching images from the `ubuntu-daily:` remote (and not from `images:`).

(As UA client has specific requirements that diverge from this sensible default behaviour, I believe its testing code should be specifically requesting an image that meets those requirements, rather than modifying the default behaviour for all consumers.)

**Comment by OddBloke** [comment]
(@TheRealFalcon FYI, this is a blocker for moving the integration tests to be voting for cloud-init, IMO: they aren't testing what they should be testing (and what the existing tests are testing).)

**Comment by TheRealFalcon** [comment]
The 'images:' remote is only being used for xenial VMs running on LXD, correct? IIRC there's an issue that prevents xenial from running on an LXD VM at all, so unless there's a reasonable workaround, it's this or no Xenial at all.

**Comment by OddBloke** [comment]
> The 'images:' remote is only being used for xenial VMs running on LXD, correct? IIRC there's an issue that prevents xenial from running on an LXD VM at all, so unless there's a reasonable workaround, it's this or no Xenial at all.

Not as of https://github.com/canonical/pycloudlib/commit/e9791a95d05116b9693249aaf2f8abee1451bd4a, no.

**Comment by OddBloke** [comment]
For reference:

```sh
$ CLOUD_INIT_OS_IMAGE=xenial tox -r -e integration-tests -- tests/integration_tests/bugs/test_lp1886531.py
...
INFO     integration_testing:conftest.py:76 Setting up environment for lxd_container
INFO     integration_testing:conftest.py:102 Done with environment setup
INFO     integration_testing:clouds.py:64 Launching instance with launch_kwargs:
image_id=images:ubuntu/16.04/cloud
user_data=#cloud-config
bootcmd:
- rm -f /etc/fstab

wait=False
```

**Comment by OddBloke** [comment]
This is now causing cloud-init integration test failures: our apt tests pass configuration which will render apt unable to update or install (specifically because we configure `squid.internal` as a proxy to test that configuration is written correctly). This means that when we attempt to install openssh-server, it fails (and we never gain SSH access to the system).

**Comment by blackboxsw** [comment]
The related PR is attempted to double-down on pycloudlib custom vm setup. If we eject this functionality from pycloudlib proper, ua-client can carry that burden in integration tests https://github.com/canonical/ubuntu-advantage-client/pull/1370. Though we should discuss further alternatives for LXD and or doc changes in pycloudlib if we can't support LXD VM xenial.

**Comment by TheRealFalcon** [comment]
This was fixed in https://github.com/canonical/pycloudlib/pull/122
