### ISSUE TITLE
pycloudlib will always install openssh-server in xenial LXD VM images

### ISSUE THREAD

**Issue by OddBloke** [canonical/pycloudlib#64]
This behaviour is not necessarily correct. Consider the following cases:

* an image has been built which _should_ have `openssh-server` installed but it doesn't
  * pycloudlib will patch over this gap, meaning that such an image could be considered good despite being fundamentally flawed
* an image has been built which is intentionally missing `openssh-server` to test how the system behaves in its absence
  * pycloudlib will install openssh-server, invalidating the test's precondition
* an image from before an openssh-server fix landed in the archive is intentionally being used to test a particular upgrade scenario
  * pycloudlib will upgrade openssh-server during cloud-init's execution, meaning that any manual "pre-upgrade" steps will happen post-upgrade

In all of these cases, installing(/upgrading) `openssh-server` unconditionally means that the tests are invalid; either their preconditions are broken, or pycloudlib is modifying the SUT in a way that means the test is effectively exercising _pycloudlib_ instead of the underlying image.

**Comment by TheRealFalcon** [comment]
This was fixed in #122
